---
# tasks to install MongoDB 3.2
- name: Add APT key
  apt_key:
    id: "EA312927"
    keyserver: keyserver.ubuntu.com
  tags: install

- name: Add APT repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2
  tags: install

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
    force_apt_get: true
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
