---
# tasks to install Ruby
- name: Install ruby and required packages in loop
  apt: "name={{ item }} state=present force_apt_get=true"
  with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
